# Generated by Django 4.0.3 on 2022-06-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_address_user_dob_user_gender_user_othername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='othername',
            new_name='other_name',
        ),
    ]
