# Generated by Django 4.0.3 on 2022-07-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentaddition_delete_student_student'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
