# Generated by Django 4.0.6 on 2022-07-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_remove_accountantaddition_dob_and_more'),
        ('transactions', '0002_alter_transaction_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accountant', to='accountant.accountant'),
        ),
    ]
