# Generated by Django 4.0.6 on 2022-07-21 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdraft',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
