# Generated by Django 4.0.6 on 2022-07-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('student', '0003_studentaddition_delete_student_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaddition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
